### ISSUE TITLE
System limitation: 32GB RAM

### ISSUE THREAD

**Issue by mguaita** [RitchieLabIGH/IRFinder#14]
Hello,

Is it possible to run IRFinder on a local computer with just 16 GB of RAM?

Thank you very much

**Comment by CloXD** [comment]
Hello Maria,
the limiting step for the RAM is the mapping with STAR. 
Using a different alignment software can be a solution to your problem, then you just have to give the BAM file as input of the "IRFinder BAM" command as described [here](https://github.com/RitchieLabIGH/IRFinder/wiki/Quantify-IR). 
Cheers,
Claudio

**Comment by mguaita** [comment]
Dear Claudio, 
Thank you, it worked just fine.

so actually, the RAM is just a requirement for the steps of building the reference (in my case I chose: "BuildRefProcess") and quantify IR from FASTQ, is that correct?.

Also, to continue with the Differential IR Analysis, I do not understand the Usage command line with DESeq2:
IRFinder Diff -g:Group1 ./Group1/Sample*/IRFinder-IR-nondir.txt -g:Group2 ./Group2/Sample*/IRFinder-IR-nondir.txt [-g:Group3 ...] 
https://github.com/RitchieLabIGH/IRFinder/wiki/Differential-IR-Analysis-With-Replicates

how do I write the command line for Diff mode including more than one sample/replica on each group? 
or is the input just one IRFinder output per group?
If so, 
¿how do I generate one IRFinder output per group with the BAM mode?

**Comment by CloXD** [comment]
Dear Maria,
yes, that's correct, all the steps that depends on STAR inherit it's RAM requirements.
For what concerns the Diff command, it's supposed to work with at least 3 samples for each group ( otherwise you can use the [Audic and Clavier test](https://github.com/RitchieLabIGH/IRFinder/wiki/No-Replicates-via-Audic-and-Claverie-Test) ) . 
The different samples for each group can be given as space separated list.
In bash the asterisk * is expanded to match the existing paths. 
In the example, suppose to have three subdirectories for each group called Sample_1, Sample_2 and Sample_3, the command
```
IRFinder Diff -g:Group1 ./Group1/Sample*/IRFinder-IR-nondir.txt -g:Group2 ./Group2/Sample*/IRFinder-IR-nondir.txt
```
Is be interpreted as:
```
IRFinder Diff -g:Group1 ./Group1/Sample_1/IRFinder-IR-nondir.txt ./Group1/Sample_2/IRFinder-IR-nondir.txt ./Group1/Sample_3/IRFinder-IR-nondir.txt  -g:Group2 ./Group2/Sample_1/IRFinder-IR-nondir.txt ./Group2/Sample_2/IRFinder-IR-nondir.txt ./Group2/Sample_3/IRFinder-IR-nondir.txt
```
Cheers,
Claudio

**Comment by mguaita** [comment]
Thank you very much Claudio!
