### ISSUE TITLE
Mappability

### ISSUE THREAD

**Issue by beaferbl** [RitchieLabIGH/IRFinder#22]
Dear Claudio,
I am generating the reference with the BuildRefFromSTARRef option, but I am not sure which MapabilityReadLength to choose. You mention this parameter in the major changes of the last version, but I do not find any information about how to set this value or which of the available precomputed files to choose. Is it maybe related to the read length of my library?
Thank you,
Bea

**Comment by CloXD** [comment]
Dear Bea,
sorry for the lack of explanation in the [wiki](https://github.com/RitchieLabIGH/IRFinder/wiki/Build-Reference): the MapabilityReadLength should be the average length of the reads used in your experiments ( in paired end experiment, consider the longest of the two pairs ). 
We decided to make it a user definable parameter to increase the flexibility of the tool.
Small remark: we maintained the misspell mapability ( one p instead of two ) for retro-compatibility.
Cheers,
Claudio

**Comment by beaferbl** [comment]
Thank you for your answer, Claudio. In that case, I have another question. As I said, I will build the reference from an already existent index generated with STAR. My reads are 150pb, but the index was generated with sjdbOverhang=100. So, should I still set MapabilityReadLength to 150?
Best,
Bea

**Comment by CloXD** [comment]
Hello Bea,
yes, the MapabilityReadLenght argument influences the regions that are not uniquely mappable and is independent by the sjdbOverhang of STAR. Those region containing repetitive elements will be excluded during the quantification of the intron coverage by IRFinder.
If I remember correctly, there are very little changes between 100 and 150 and the impact on the final results is marginal.
Cheers,
Claudio

**Comment by beaferbl** [comment]
Now everything is clear. Thank you for your time!
