### ISSUE TITLE
Quick question about two outputs: idr v.s. nonidr

### ISSUE THREAD

**Issue by progistar** [RitchieLabIGH/IRFinder#37]
Dear IRFinder's team,

Hi, I have a quick question about idr v.s. nonidr.
In my understanding, the number records in nonidr should be larger than idr.
However, some of my data do not look like.

It would be great if you could let me know.

Best,

Seunghyuk Choi

**Comment by CloXD** [comment]
Dear Seunghyuk Choi,
the difference between the two is that in the directional, the features excluded are the ones on the same strand, meanwhile the nondir excludes features on both strands. 
Therefore, if a feature ( let's say, the exon of another gene ) is on the opposite strand and covers the whole intron, the nondir won't report that intron because it is all masked by the exon on the opposite strand, meanwhile the directional will have it because it's ignoring the opposite strand. 
I hope this answer your question. 
Cheers,
Claudio

**Comment by progistar** [comment]
@CloXD Thanks for your reply! It is very helpful to understand.
