### ISSUE TITLE
error while loading shared libraries: libboost_iostreams.so.1.65.1

### ISSUE THREAD

**Issue by yannnnLi** [RitchieLabIGH/IRFinder#7]
Hi !
I used IRFinder-S to identify IR enents in my sample. At the step of quantifying IR, I met an error reported in irfinder.stderr.
```
/public/home/liunangroup/liangyan/pipeline/IRFinder-2.0-beta/bin/IRFinder \
 -m BAM \
 -r ./REF/GRCh38 \
 -t 20 \
 -d ~/IR/WT2 \
 ~/IR/WT2/Unsorted.bam
```
```
/public/home/liunangroup/liangyan/pipeline/IRFinder-2.0-beta/bin/util/irfinder: error while loading shared libraries: libboost_iostre
ams.so.1.65.1: cannot open shared object file: No such file or directory
```
However, I had created an conda environment for IRFinder, installed libboost_iostreams.so.1.65.1 and activated the IRFinder. Notably, I    had tried to compile the IRFinder through "./install.sh local" in the IRFinder environment.
However, it also showed that
```
Checking dependencies...
Dependency bedtools not found.
Dependency samtools not found.
Dependency libboost-iostreams-dev not found.
Dependency zlib1g not found.
```

I am confused about these result, because I have install the dependency of IRFinder-S.

I am looking forward your reply.
Liang yan

**Comment by CloXD** [comment]
Hello Liang,
sorry for the late answer.
For what concerns the dependencies errors, I think the problem is that the install script checks the dependencies using dpkg ( under Ubuntu or Debian system ) or rpm ( otherwise ) and if you are using it under a conda environment, I'm not sure that it's going to detect them as installed in the environment.
For what concerns the libboost_iostreams library, I think it's a problem linked to the shared library ( https://docs.conda.io/projects/conda-build/en/latest/resources/use-shared-libraries.html ), so you should set the LD_LIBRARY_PATH adding the conda environment one.
As usual, I suggest whenever possible the use of docker or singularity to avoid this type of problem and improve the reproducibility of the results.
Hoping this helped, let me know if this was helpful.
Cheers,
Claudio

**Comment by yannnnLi** [comment]
Hello Claudio,
Thanks for your reply.
It do works after adding the lib of conda environment to LD_LIBRARY_PATH through
```
export LD_LIBRARY_PATH=~/miniconda3/envs/IRFinder/lib
```
By the way, I really want to use a container to configure environments for several pipelines, but docker or singularity has not been installed in our HPC. (T.T)
Have a good weekend.
Liang yan

**Comment by CloXD** [comment]
Hello Liang,
I'm glad it worked! 
Usually, system administrators are happy to install them since it means fewer dependency library requests on their side ;) 
Have a good weekend you too,
Claudio
